Script mode

diff --git a/libexec/bravia/setup b/libexec/bravia/setup
--- a/libexec/bravia/setup
+++ b/libexec/bravia/setup
@@ -1,10 +1,16 @@
 #!/usr/bin/env bash
 
+script="$1"
+
 cd "$(dirname "${BASH_SOURCE[0]}")"
 
 ip=$(cat .ip | egrep -o "([0-9]{1,3}\.){3}[0-9]{1,3}")
 
 if [[ -z "$ip" ]]; then
+  if [ "$script" == true ]; then
+    echo "Script mode, cannot select IP"
+    exit 1
+  fi
   ./selectIp
   ip=$(cat .ip | egrep -o "([0-9]{1,3}\.){3}[0-9]{1,3}")
 fi
